### ISSUE TITLE
Don't prepend protocol to http_proxy or https_proxy

### ISSUE THREAD

**Issue by JasonBarnabe** [SquareSquash/ruby#12]
squash_ruby is prepending `http://` and `https://` to  the values for http_proxy and https_proxy. These values [normally](https://wiki.archlinux.org/index.php/Proxy_settings) already contain the protocol, which means this setting doesn't work.

https://github.com/SquareSquash/ruby/blob/62b890e62f062158a92e09e5ba0f29df01032356/lib/squash/ruby.rb#L334-L342

**Comment by RISCfuture** [comment]
If you want to create a quick PR I can approve it; otherwise I'll get to it soon™.

**Comment by JasonBarnabe** [comment]
@RISCfuture can you put out a release with this change?
